version: '3.8'

services:
  nlp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nlp-bootcamp
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/code/notebooks
    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --NotebookApp.token=''
